### PR TITLE
fix layout colors to be exactly they are in PSD

### PR DESCRIPTION
**Pull request by viniciusdacal**
issue #16

### CODE REVIEW

**Comment by jaydson** [comment]
Thanks @viniciusdacal !
Please check @robsongajunior

**Comment by robsongajunior** [comment]
@jaydson, i'm looking too.

We need modify some things after review colors.
Tonight me and @viniciusdacal lets talk about this.

**Comment by robsongajunior** [comment]
**Merged** at master branch.
Congratulations to your work.
Good job :)

**Comment by viniciusdacal** [comment]
Thanks Man :smiley:

**Pull request merged**
