### PR TITLE
Change font default from 'nexa_boldregular' to 'nexa_lightregular'

### PR DESCRIPTION
**Pull request by viniciusdacal**
Change font default to be exactly like PSD.
issue #16

### CODE REVIEW

**Comment by jaydson** [comment]
//cc @robsongajunior

**Comment by robsongajunior** [comment]
i'm looking.

**Comment by robsongajunior** [comment]
Hmmm, so...
On PSD it is with bold select, we can see in the image below.

printboldfont

So, let's compare, below.

**Bold**
bold

**without bold**
nobold

---

Without bold it's hard to read. font-weight bold is more legible!!
@italowaxman can you help us?

**Comment by viniciusdacal** [comment]
In your PSD is Nexa Light too.
But I agree with you, to small font-size texts is harder to read. The problem is that browsers render font-smoth very different from photoshop in some cases.

**Comment by viniciusdacal** [comment]
Maybe we could let nexa bold to small font-sizes as 14px and use nexa light to bigger fonts.
captura de tela 2015-07-08 as 13 45 25
captura de tela 2015-07-08 as 13 45 50

**Comment by robsongajunior** [comment]
@viniciusdacal  pay attention at the last select.

**Nexa Light  - regular - 15pt - strong**

I will make some tests to be nearer.

**Comment by viniciusdacal** [comment]
Yes @robsongajunior , but **strong** there is just the font antialiasing.
By the way, do you have some task I can help you with?

**Comment by jaydson** [comment]
@italowaxman please help us here.
@robsongajunior please split the job with @viniciusdacal

**Comment by robsongajunior** [comment]
@jaydson ....
of course, will be fun.

@viniciusdacal add me:

facebook.com/robsongajunior - facebook
robson.ga.junior@gmail.com - gtalk

Today at night, let's talk about this.

**Comment by viniciusdacal** [comment]
yep :)

**Comment by robsongajunior** [comment]
fixed

**Pull request closed without merging**
